version: 2

sources:
  - name: spotify_raw
    description: Raw Spotify data loaded in to warehouse via etl
    database: postgres
    schema: spotify_raw
    loader: etl.py
    tables:
      - name: endsong
        description: Streaming data
        columns:
          - name: ts
            description: add later
            tests:
              - not_null
          - name: username
            description: add later
            tests:
              - not_null
          - name: platform
            description: add later
            tests:
              - not_null
          - name: ms_played
            description: add later
            tests:
              - not_null
          - name: conn_country
            description: add later
            tests:
              - not_null
          - name: ip_addr_decrypted
            description: add later
            tests:
              - not_null
          - name: user_agent_decrypted
            description: add later
            tests:
              - not_null
          - name: master_metadata_track_name
            description: add later
          - name: master_metadata_album_artist_name
            description: add later
          - name: master_metadata_album_album_name
            description: add later
          - name: spotify_track_uri
            description: add later
          - name: episode_name
            description: add later
          - name: episode_show_name
            description: add later
          - name: spotify_episode_uri
            description: add later
          - name: reason_start
            description: add later
            tests:
              - not_null
          - name: reason_end
            description: add later
            tests:
              - not_null
          - name: shuffle
            description: add later
            tests:
              - not_null
              - accepted_values:
                  values: ['true', 'false']
          - name: skipped
            description: add later
            tests:
              - accepted_values:
                  values: ['True', 'False', null]
          - name: offline
            description: add later
            tests:
              - not_null
              - accepted_values:
                  values: ['true', 'false']
          - name: offline_timestamp
            description: add later
            tests:
              - not_null
          - name: incognito_mode
            description: add later
            tests:
              - not_null
              - accepted_values:
                  values: ['true', 'false']
