name: "the_auditory_almanac"
config-version: 2
version: 1.3.2

profile: "the_auditory_almanac"
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
docs-paths: ["docs"]
asset-paths: ["assets"]

target-path: "target"
log-path: "logs"

clean-targets:
  - "target"

models:
  the_auditory_almanac:
    materialized: table
