version: 2

models:
  - name: albums
    description: add later
    columns:
      - name: id
        description: add later
        tests:
          - not_null
          - unique
      - name: album
        description: add later
        tests:
          - not_null
      - name: artist
        description: add later
        tests:
          - not_null
      - name: num_streams
        description: add later
        tests:
          - not_null
      - name: num_uris_streamed
        description: add later
        tests:
          - not_null
      - name: first_stream
        description: add later
        tests:
          - not_null
      - name: most_recent_stream
        description: add later
        tests:
          - not_null
      - name: total_ms_played
        description: add later
        tests:
          - not_null
      - name: uris
        description: add later
        tests:
          - not_null
          - unique
      - name: avg_ms_played
        description: add later
        tests:
          - not_null

  - name: tracks
    description: add later
    columns:
      - name: id
        description: add later
        tests:
          - not_null
          - unique
      - name: track
        description: add later
        tests:
          - not_null
      - name: artist
        description: add later
        tests:
          - not_null
      - name: num_uris
        description: add later
        tests:
          - not_null
      - name: num_albums
        description: add later
        tests:
          - not_null
      - name: first_stream
        description: add later
        tests:
          - not_null
      - name: most_recent_stream
        description: add later
        tests:
          - not_null
      - name: total_ms_played
        description: add later
        tests:
          - not_null
      - name: uris
        description: add later
        tests:
          - not_null
          - unique
      - name: avg_ms_played
        description: add later
        tests:
          - not_null