version: 2

models:
  - name: albums_all_time
    description: add later
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - album_id
            - album
            - artist
    columns:
      - name: album_id
        description: add later
        tests:
          - not_null
          - unique
      - name: album
        description: add later
        tests:
          - not_null
      - name: artist
        description: add later
        tests:
          - not_null
      - name: num_uris_streamed
        description: add later
        tests:
          - not_null
      - name: uris
        description: add later
        tests:
          - not_null
          - unique
      - name: num_streams
        description: add later
        tests:
          - not_null
      - name: first_stream
        description: add later
        tests:
          - not_null
      - name: most_recent_stream
        description: add later
        tests:
          - not_null
      - name: total_ms_played
        description: add later
        tests:
          - not_null
      - name: avg_ms_played
        description: add later
        tests:
          - not_null
      - name: days_between_streams
        description: add later
      - name: streams_per_day
        description: add later

  - name: albums_monthly
    description: add later
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - album_id
            - album
            - artist
            - month
    columns:
      - name: album_id
        description: add later
        tests:
          - not_null
      - name: album
        description: add later
        tests:
          - not_null
      - name: artist
        description: add later
        tests:
          - not_null
      - name: month
        description: add later
        tests:
          - not_null
      - name: num_streams
        description: add later
        tests:
          - not_null
      - name: first_stream
        description: add later
        tests:
          - not_null
      - name: most_recent_stream
        description: add later
        tests:
          - not_null
      - name: total_ms_played
        description: add later
        tests:
          - not_null
      - name: avg_ms_played
        description: add later
        tests:
          - not_null
      - name: days_between_streams
        description: add later
      - name: streams_per_day
        description: add later

  - name: albums_yearly
    description: add later
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - album_id
            - album
            - artist
            - year
    columns:
      - name: album_id
        description: add later
        tests:
          - not_null
      - name: album
        description: add later
        tests:
          - not_null
      - name: artist
        description: add later
        tests:
          - not_null
      - name: year
        description: add later
        tests:
          - not_null
      - name: num_streams
        description: add later
        tests:
          - not_null
      - name: first_stream
        description: add later
        tests:
          - not_null
      - name: most_recent_stream
        description: add later
        tests:
          - not_null
      - name: total_ms_played
        description: add later
        tests:
          - not_null
      - name: avg_ms_played
        description: add later
        tests:
          - not_null
      - name: days_between_streams
        description: add later
      - name: streams_per_day
        description: add later